#!/usr/bin/env bash
set -euo pipefail

project_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
report_dir="$project_dir/reports"
activity_file="$project_dir/data/activity.log"
report_file="$report_dir/daily-status.md"

mkdir -p "$report_dir"
activity_count=$(wc -l < "$activity_file" | tr -d ' ')
latest_activity=$(tail -n 1 "$activity_file")

cat > "$report_file" <<EOF
# Daily status

Generated by the Codex Local Scheduler demo workflow.

- Recorded activities: $activity_count
- Latest activity: $latest_activity
- Scheduler project: ${CODEX_LOCAL_SCHEDULER_PROJECT:-not provided}
EOF

printf 'Wrote %s\n' "$report_file"
